//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventApp.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserOrder()
        {
            this.Orders = new HashSet<Order>();
        }

        public string GetInfo
        {
            get
            {
                return "Номер заказ: " + UOrderID + ", клиент: " + UserID;
            }
        }

        public string GetColor
        {
            get
            {
                if (StatusID == 1)
                {
                    return "#e89607";
                }
                else if (StatusID == 2)
                {
                    return "#07e82c";
                }
                else if (StatusID == 3)
                {
                    return "#e82107";
                }
                return "";
            }
        }

        public int UOrderID { get; set; }
        public int UserID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrgDate { get; set; }
        public double Deposit { get; set; }
        public double TotalPrice { get; set; }
        public int PlaceID { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Place Place { get; set; }
        public virtual Service Service { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
